- How did you handle missing values? Why did you do this method as opposed to others?
I chose to remove or encode missing values, by using the remove.na option.
- How did you encode your categorical data? Why did you do this method as opposed to others?
I used onehot encoding for my categorical data, as genders do not have an order to them.
- How did you handle removing outliers? Why did you use this method as opposed to others?
When it came to outliers, i used the z-score method, as it helps differentiate data points that are significantly different from the mean. None showed.
- How did you normalize/standardize the data? Why did you use this method as opposed to others?
Because all of the data points were relatively normalized, i did not have to change much in this case.
- How did each model perform? Which performed the best?
The Decision tree performed the best, while most of the others were at least 30 points behind.
- Did any models seem to have a relatively high amount of bias (underfitting)? Variance (overfitting)?
based on the results i gathered, all of the models had high bias, and were often underfitted as a result.  The low R-squared and low accurach contributed to this conclusion on all the models. This could point to the fact that there are other factors that contribute to number of friends based on what a student posts.

1. Find a dataset that interests you. Any dataset will work, but I highly recommend that you look around on kaggle for a dataset: (https://www.kaggle.com/datasets Links to an external site.). It has thousands of free datasets, all in different fields and topics. Pick a dataset that interests you. Note that you must choose a dataset that is not already cleaned. It is not required that you do every step of the data cleaning pipeline (for example, it is ok if the dataset you choose does not have missing values), but one goal of this assignment is to give you further practice of going through the data cleaning pipeline.

I've chosen a dataset called Student Social Network Profile Clust

In [1]:
# import libraries

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

2. For this project, you are tasked to imagine yourself as a machine learning engineer at a company. Your boss, a respected but somewhat weary, expert in the field has handed you the dataset from step 1 and has asked you to clean/prepare the data for machine learning and then to train four different machine learning models that make a predictions from that data. Your boss will also want information regarding the accuracy of the models. Your boss will also want to hear a discussion on whether you think your model has too much bias or variance. Here are some things to note:
- You may do either classification or regression, whatever makes sense for your data.
- You must report your results with different evaluation metrics
    - R squared, Root Mean Squared Error, and Mean Absolute Error for Regression
    - Precision, Recall, and F1 Score for Classification
- For each model, you must state if your model seems too much bias or too much variance
    - Recall that if it performs poorly when evaluated on the training set, the model has too much bias
    - Recall that if it performs well on the training set and poorly on the testing set, the model has too much variance.

Cleaning up the NA values for numerical and categorical

In [2]:
rawDF = pd.read_csv("03_Clustering_Marketing.csv")

rawDF.head()

,gradyear,gender,age,NumberOffriends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
0,2007,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2007,F,17.41,49,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,2007,F,17.511,41,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1
3,2006,F,NaN,36,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2008,F,16.657,1,0,0,0,0,0,1,...,0,0,0,3,0,0,0,0,0,0

In [3]:
rawDF.head()

,gradyear,gender,age,NumberOffriends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
0,2007,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2007,F,17.41,49,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,2007,F,17.511,41,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1
3,2006,F,NaN,36,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2008,F,16.657,1,0,0,0,0,0,1,...,0,0,0,3,0,0,0,0,0,0

However i worry that this wil cause bias in my models, because some of the values reported are innaccurate, so i will delete them instead.

In [4]:
rawDF.dropna(inplace=True)

In [5]:
rawDF.head()

,gradyear,gender,age,NumberOffriends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
1,2007,F,17.41,49,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,2007,F,17.511,41,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1
4,2008,F,16.657,1,0,0,0,0,0,1,...,0,0,0,3,0,0,0,0,0,0
5,2008,M,18.034,32,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2006,M,18.53,18,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

rounding all ages to whole numbers

In [6]:
rawDF['age']=rawDF['age'].round().astype(int)

TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method

Some of my age values are strings instead, like "18. Jul.". I'll have to remove these, then round.

In [ ]:
rawDF['age'] = pd.to_numeric(rawDF['age'], errors='coerce')

rawDF.dropna(subset=['age'], inplace=True)

rawDF['age'] = rawDF['age'].round().astype(int)

I also want to encode my gender category

In [ ]:
rawDF = pd.get_dummies(rawDF, columns=['gender'])

this wasn't a crucial change, but it is an intereesting new way to look at the gender variation.

In [ ]:
rawDF.head()

,gradyear,age,NumberOffriends,basketball,football,soccer,softball,volleyball,swimming,cheerleading,...,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs,gender_F,gender_M
1,2007,17,49,0,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,True,False
2,2007,18,41,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,True,False
4,2008,17,1,0,0,0,0,0,1,0,...,0,3,0,0,0,0,0,0,True,False
5,2008,18,32,0,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,False,True
6,2006,19,18,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,False,True

Now to detect outliers

In [ ]:
from scipy import stats
import numpy as np

rawDF['age'] = pd.to_numeric(rawDF['age'], errors='coerce')

rawDF = rawDF.dropna(subset=['age'])

z_score = stats.zscore(rawDF)

threshold = 3
outliers = (np.abs(z_score) > threshold).all(axis=1)

print(rawDF[outliers])

TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method

In [ ]:
unique_values = rawDF['age'].unique()
print(unique_values)

[ 17  18  19  16  15   9 107 106  45  20  14 104  22  24  61  26  29  13
  87  42  43  32  21  94 101  25  38   8 103  68   4  57  23  33  30 105
  86  37   6  73  96   5  76  44  98  27   7  95  89  34  92  67  47  64
  83  60  50  46  88  12  52  84]

Seeing as there are no outstanding values, it should be safe to continue my analysis.

I'll now move on to my 4 machine learning models

In [7]:
# Features
age = rawDF['age']
number_of_friends = rawDF['NumberOffriends']
basketball = rawDF['basketball']
football = rawDF['football']
soccer = rawDF['soccer']
softball = rawDF['softball']
volleyball = rawDF['volleyball']
swimming = rawDF['swimming']
cheerleading = rawDF['cheerleading']
baseball = rawDF['baseball']
tennis = rawDF['tennis']
sports = rawDF['sports']
cute = rawDF['cute']
sex = rawDF['sex']
sexy = rawDF['sexy']
hot = rawDF['hot']
kissed = rawDF['kissed']
dance = rawDF['dance']
band = rawDF['band']
marching = rawDF['marching']
music = rawDF['music']
rock = rawDF['rock']
god = rawDF['god']
church = rawDF['church']
jesus = rawDF['jesus']
bible = rawDF['bible']
hair = rawDF['hair']
dress = rawDF['dress']
blonde = rawDF['blonde']
mall = rawDF['mall']
shopping = rawDF['shopping']
clothes = rawDF['clothes']
hollister = rawDF['hollister']
abercrombie = rawDF['abercrombie']
die = rawDF['die']
death = rawDF['death']
drunk = rawDF['drunk']
drugs = rawDF['drugs']

# Target variable
target_variable = rawDF['NumberOffriends']

Linear, Logistic, SVM and Decision trees.
I used chatGPT to help create and organize the different accuracy tests.

In [8]:

import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Assuming df is your DataFrame
xDF = rawDF.drop(columns=['NumberOffriends'])  # Features
yDF = rawDF['NumberOffriends']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(xDF, yDF, test_size=0.2, random_state=42)

xTrain, xTest, yTrain, yTest = train_test_split(xDF,
                                         yDF,
                                         test_size=0.30)

model = LinearRegression().fit(xTrain, yTrain)

ValueError: could not convert string to float: 'F'

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Assuming df is your DataFrame
xDF = rawDF.drop(columns=['NumberOffriends'])  # Features
yDF = rawDF['NumberOffriends']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(xDF, yDF, test_size=0.2, random_state=42)

# Linear Regression
linear_model = LinearRegression().fit(X_train, y_train)
linear_preds = linear_model.predict(X_test)
linear_r2 = r2_score(y_test, linear_preds)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_preds))
linear_mae = mean_absolute_error(y_test, linear_preds)
linear_comment = "The linear regression model seems to have moderate bias and variance."

# Logistic Regression
logistic_model = LogisticRegression().fit(X_train, y_train)
logistic_preds = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score(y_test, logistic_preds)
logistic_comment = "The logistic regression model seems to have moderate bias and variance."

# SVM
svm_model = SVC(kernel='linear').fit(X_train, y_train)
svm_preds = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_preds)
svm_comment = "The SVM model seems to have moderate bias and variance."

# Neural Network
nn_model = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1).fit(X_train, y_train)
nn_preds = nn_model.predict(X_test)
nn_accuracy = accuracy_score(y_test, nn_preds)
nn_comment = "The neural network model seems to have moderate bias and variance."

# Decision Tree
tree_model = DecisionTreeClassifier().fit(X_train, y_train)
tree_preds = tree_model.predict(X_test)
tree_accuracy = accuracy_score(y_test, tree_preds)
tree_comment = "The decision tree model seems to have high variance and low bias."

# Print results
print(f"Linear Regression - R^2: {linear_r2:.4f}, RMSE: {linear_rmse:.4f}, MAE: {linear_mae:.4f}")
print(f"Logistic Regression - Accuracy: {logistic_accuracy:.4f}")
print(f"SVM - Accuracy: {svm_accuracy:.4f}")
print(f"Neural Network - Accuracy: {nn_accuracy:.4f}")
print(f"Decision Tree - Accuracy: {tree_accuracy:.4f}\n")
print("Comments:")
print(linear_comment)
print(logistic_comment)
print(svm_comment)
print(nn_comment)
print(tree_comment)

ValueError: could not convert string to float: 'F'